version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: peranto_user
      POSTGRES_PASSWORD: peranto_pass
      POSTGRES_DB: peranto_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://peranto_user:peranto_pass@postgres:5432/peranto_db
      # Aquí puedes agregar más variables de entorno necesarias, o usar un archivo .env
    ports:
      - '4000:4000'
    command: ["yarn", "start"]
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'
    command: ["yarn", "start"]
    restart: always

volumes:
  pgdata: 